### ISSUE TITLE
error Unsupported protocol: remote: service:jmx:remote

### ISSUE THREAD

**Issue by gomin1d** [hermanekt/zabbix_get_jmx#1]
command
```
zabbix_get_jmx --java-gateway-host 127.0.0.1 --java-gateway-port 10052 --jmx-server 117.50.1.117 --jmx-port 20421 --jmx-user controlRole --jmx-pass pass --new-protocol --key 'jmx.discovery[beans,"*:type=GarbageCollector,name=*"]'
```

output 
```
{"response":"failed","error":"Unsupported protocol: remote: service:jmx:remote:\/\/117.50.1.117:20421\/"}
```

**Comment by gomin1d** [comment]
to fixed:
```
    query['jmx_endpoint'] = 'service:jmx:rmi:///jndi/rmi://%s:%s/jmxrmi' % (conn, port)
```

**Comment by hermanekt** [comment]
Please try first this command (without --new-protocol)
```
zabbix_get_jmx --java-gateway-host 127.0.0.1 --java-gateway-port 10052 --jmx-server 117.50.1.117 --jmx-port 20421 --jmx-user controlRole --jmx-pass pass --key 'jmx.discovery[beans,"*:type=GarbageCollector,name=*"]'
```

**Comment by gomin1d** [comment]
in this case
```
{"response":"failed","error":"No value for jmx_endpoint"}
```

**Comment by hermanekt** [comment]
Thank you, i do fix for both version tomorrow.

**Comment by hermanekt** [comment]
Can you please tell me your OS and python version? Thank you Tom

**Comment by gomin1d** [comment]
> Can you please tell me your OS and python version? Thank you Tom

debian 9  
Python 3.6.10

**Comment by hermanekt** [comment]
Thank you, can you please check zabbix and wildfly version too?

**Comment by hermanekt** [comment]
You can check updated version in git  without parameter script use old version.

```
zabbix_get_jmx --java-gateway-host 127.0.0.1 --java-gateway-port 10052 --jmx-server 117.50.1.117 --jmx-port 20421 --jmx-user controlRole --jmx-pass pass --key 'jmx.discovery[beans,"*:type=GarbageCollector,name=*"]'
```

**Comment by gomin1d** [comment]
> Thank you, can you please check zabbix and wildfly version too?

zabbix-server-mysql 1:5.0.10-1+stretch  
zabbix-java-gateway 1:5.0.10-1+stretch  
wildfly not installed

**Comment by gomin1d** [comment]
> You can check updated version in git without parameter script use old version.
> 
> ```
> zabbix_get_jmx --java-gateway-host 127.0.0.1 --java-gateway-port 10052 --jmx-server 117.50.1.117 --jmx-port 20421 --jmx-user controlRole --jmx-pass pass --key 'jmx.discovery[beans,"*:type=GarbageCollector,name=*"]'
> ```

works successfully

**Comment by hermanekt** [comment]
In my lab i have Debian 10, zabbix 5.4beta2, python 3.7 and i have problem with running script with different error like you. I need more time for fixing this. Im not originally owner of this script. I want add support for both version, old and new.  Can you please check latest version of this script in the git please?

**Comment by gomin1d** [comment]
> In my lab i have Debian 10, zabbix 5.4beta2, python 3.7 and i have problem with running script with different error like you. I need more time for fixing this. Im not originally owner of this script. I want add support for both version, old and new. Can you please check latest version of this script in the git please?

checked

with the --new-protocol flag does not work, error:
```
{"response":"failed","error":"Unsupported protocol: remote: service:jmx:remote:\/\/117.50.1.117:20421\/"}
```

without the --new-protocol flag, it works successfully, the output is:
```
{"data":[{"value":"{\"data\":[{\"{#JMXDOMAIN}\":\"java.lang\",\"{#JMXTYPE}\":\"GarbageCollector\",\"{#JMXOBJ}\":\"java.lang:type=GarbageCollector,name=PS MarkSweep\",\"{#JMXNAME}\":\"PS MarkSweep\"},{\"{#JMXDOMAIN}\":\"java.lang\",\"{#JMXTYPE}\":\"GarbageCollector\",\"{#JMXOBJ}\":\"java.lang:type=GarbageCollector,name=PS Scavenge\",\"{#JMXNAME}\":\"PS Scavenge\"}]}"}],"response":"success"}
```

**Comment by hermanekt** [comment]
Thank you, this fix seem work for you, i have some environment issue.
